package presentation.resources

data class StringResources(
    val start: String = "start",
    val mainScreenTitle: String = "Foodies are waiting!",
    val mainScreenSubTitle: String = "Tap Start and become their food superhero",
    val welcomeToBeepBeepApp: String = "Welcome To Beep Beep App",
    val loginToAccessAllTheFeatures: String = "Login to access all the features",
    val username: String = "Username",
    val password: String = "Password",
    val keepMeLoggedIn: String = "Keep me logged in",
    val login: String = "Login",
    val signUpWithYourBeepBeepAccount: String = "Sign up with your Beep Beep account",
    val wrongPermission: String = "Wrong permission",
    val wrongPermissionSheetDescription: String = "Looks like  your account isn’t assigned as a restaurant owner, ask for permission?",
    val requestAPermission: String = "Request a permission",
    val askForPermission: String = "Ask for permission",
    val fullName: String = "Full name",
    val userEmail: String = "User email",
    val whyBeepBeep: String = "Why beep beep?",
    val describeWhyYouWantToJoinUs: String = "Describe why you want to join us",
    val submit: String = "Submit",
    val yourRequestSubmittedSuccessfully: String = "Your request submitted successfully",
    val weWillContactYouLaterViaEmail: String = "We will contact you later via email.",
    val findingRequest: String = "Finding ride requests",
    val mapScreenAppBarTitle: String = "Welcome, ",
    val newOrder: String = "New Order",
    val acceptRequest: String = "Accept Request",
    val cancel: String = "Cancel",
    val arrived: String = "Arrived",
    val pickUp: String = "Pick up",
    val dropOff: String = "Drop off",
    val close: String = "Close",
)
