package resources.strings.en

import resources.strings.IStringResources

data class English(
    override val beepBeep: String = "Beep Beep",
    override val backgroundDescription: String = "background image",
    override val loginWelcomeMessage: String = "Welcome To Beep Beep App",
    override val loginSubWelcomeMessage: String = "Login to access all the features",
    override val usernameLabel: String = "Username",
    override val passwordLabel: String = "Password",
    override val login: String = "Login",
    override val keepMeLoggedIn: String = "Keep me logged in",
    override val signUpNow: String = "Sign up now",
    override val signUpDescription: String = "Don't have an account ?",
    override val home: String = "Home",
    override val search: String = "Search",
    override val orders: String = "Orders",
    override val notification: String = "Notification",
    override val profile: String = "Profile",
    override val cuisineImageDescription: String = "image",
    override val viewAll: String = "View all",
    override val seeAllDescription: String = "view all icon",
    override val cuisineSectionTitle: String = "Cuisine",
    override val haveQuestions: String = "Have Questions ?",
    override val connectWithSupport: String = "Connect with Support",
    override val connectWithSupportIconDescription: String = "connect with support text icon",
    override val orderCardImageDescription: String = "Order card image",
    override val orderTaxiButtonTitle: String = "Order taxi",
    override val orderFoodButtonTitle: String = "Order food",
    override val wallet: String = "Wallet",
    override val welcome: String = "Welcome",
    override val off: String = "Off",
    override val favoriteRestaurants: String = "Favorite restaurants",
    override val eidSpecials: String = "Eid specials",
    override val freeDelivery: String = "Free delivery",
    override val deliciousItemsInYourCart: String = "Delicious items in your cart!",
    override val clickHereAndCompleteYourOrder: String = "Click here and Complete your order.",
    override val taxiOnTheWay: String = "Your taxi is on the way...",
    override val enjoyYourRide: String = "Enjoy your ride!",
    override val orderOnTheWay: String = "Your order is on the way...",
    override val inProgress: String = "In progress",
    override val lastOrder: String = "Last order",
    override val orderAgain: String = "Order again",
    override val dishPreferredTitle: String = "Which dish do you prefer?",
    override val dishPreferredSubTitle: String = "Tell us your preferences to help you.",
    override val lowPriceLevel: String = "$",
    override val mediumPriceLevel: String = "$$",
    override val highPriceLevel: String = "$$$",
    override val lowLevelDishName: String = "Classic Pasta Dish",
    override val mediumLevelDishName: String = "Exceptional Sauce Pasta Dish",
    override val highLevelDishName: String = "Healthy (gulten free) Pasta",
    override val searchHint: String = "Search for meal, restaurant",
    override val invalidUsername: String = "invalid username"
) : IStringResources