package resources

data class StringResources(
    val beepBeep: String = "Beep Beep",
    val backgroundDescription: String = "background image",
    val loginWelcomeMessage: String = "Welcome To Beep Beep App",
    val loginSubWelcomeMessage: String = "Login to access all the features",
    val usernameLabel: String = "Username",
    val passwordLabel: String = "Password",
    val login: String = "Login",
    val keepMeLoggedIn: String = "Keep me logged in",
    val signUpNow: String = "Sign up now",
    val signUpDescription: String = "Don't have an account ?",
    val home: String = "Home",
    val search: String = "Search",
    val orders: String = "Orders",
    val notification: String = "Notification",
    val profile: String = "Profile",
    val cuisineImageDescription: String = "image",
    val viewAll: String = "View all",
    val seeAllDescription: String = "view all icon",
    val cuisineSectionTitle: String = "Cuisine",
    val haveQuestions: String = "Have Questions ?",
    val connectWithSupport: String = "Connect with Support",
    val connectWithSupportIconDescription: String = "connect with support text icon",
    val orderCardImageDescription: String = "Order card image",
    val orderTaxiButtonTitle: String = "Order taxi",
    val orderFoodButtonTitle: String = "Order food",
    val off: String = "Off",
    val favoriteRestaurants: String = "Favorite restaurants",
    val eidSpecials: String = "Eid specials",
    val freeDelivery: String = "Free delivery"
)
