package org.thechance.service_identity.endpoints.validation

const val ERROR_CODE_NOT_FOUND = 1041
const val ERROR_CODE_INVALID_HEX_STRING_LENGTH = 1043


const val ERROR_CODE_INVALID_USER_ID = 1044
const val ERROR_CODE_INVALID_ADDRESS_ID = 1042
const val ERROR_CODE_INVALID_ADDRESS_LOCATION = 1045


const val ERROR_USER_ALREADY_EXISTS = 1002
const val ERROR_CODE_INVALID_FULLNAME = 1003
const val ERROR_CODE_INVALID_USERNAME = 1004

const val INVALID_PERMISSION_ID_ERROR_CODE = "1061"
const val NOT_FOUND_ERROR_CODE = "1041"