package resources.strings

interface IStringResources {
    val yourAddress: String
    val invalidAddress: String
    val unknownError: String
    val wifiDisabled: String
    val requestFailed: String
    val noInternet: String
    val invalidPhoneNumber: String
    val invalidEmail: String
    val invalidFullName: String
    val oppsRegistrationNotCompleted: String
    val beepBeep: String
    val backgroundDescription: String
    val loginWelcomeMessage: String
    val loginSubWelcomeMessage: String
    val usernameLabel: String
    val passwordLabel: String
    val login: String
    val keepMeLoggedIn: String
    val signUpNow: String
    val signUpDescription: String
    val home: String
    val search: String
    val orders: String
    val notification: String
    val profile: String
    val cuisineImageDescription: String
    val allCuisines: String
    val viewAll: String
    val seeAllDescription: String
    val cuisineSectionTitle: String
    val haveQuestions: String
    val connectWithSupport: String
    val connectWithSupportIconDescription: String
    val orderCardImageDescription: String
    val orderTaxiButtonTitle: String
    val orderFoodButtonTitle: String
    val wallet: String
    val welcome: String
    val off: String
    val favoriteRestaurants: String
    val eidSpecials: String
    val freeDelivery: String
    val deliciousItemsInYourCart: String
    val clickHereAndCompleteYourOrder: String
    val taxiOnTheWay: String
    val enjoyYourRide: String
    val orderOnTheWay: String
    val inProgress: String
    val lastOrder: String
    val orderAgain: String
    val dishPreferredTitle: String
    val dishPreferredSubTitle: String
    val lowPriceLevel: String
    val mediumPriceLevel: String
    val highPriceLevel: String
    val lowLevelDishName: String
    val mediumLevelDishName: String
    val highLevelDishName: String
    val searchHint: String
    val invalidUsername: String
    val invalidPassword: String
    val languageAskAboutLanguage: String
    val selectLanguage: String
    val joinBpToday: String
    val createYourAccount: String
    val next: String
    val justOnMoreStep: String
    val completeYourRegistration: String
    val fullName: String
    val email: String
    val mobileNumber: String
    val signUp: String
    val username: String
    val password: String
    val ridePreferredTitle: String
    val ridePreferredSubTitle: String
    val quickerRoutesWithHigherCosts: String
    val slowerRoutesWithLowCosts: String
    val today: String
    val thisWeek: String
    val tryAgain: String
    val trackYourOrder: String
    val logout: String
    val address: String
    val save: String
    val history: String
    val orderNow: String
    val total: String
    val yourCart: String
    val pleaseLogin: String
}